insert into groups (group_name) values ('YS-27');
insert into groups (group_name) values ('HV-14');
insert into groups (group_name) values ('QM-09');
insert into groups (group_name) values ('ZF-83');
insert into groups (group_name) values ('RG-52');
insert into groups (group_name) values ('PL-41');
insert into groups (group_name) values ('KX-76');
insert into groups (group_name) values ('ND-98');
insert into groups (group_name) values ('TC-63');
insert into groups (group_name) values ('WU-48');
insert into groups (group_name) values ('Students without group');
